todo_manager/todo_list/urls.py
from django.urls import path
from django.views.generic import TemplateView
from . import views

app_name = 'todo_list'

urlpatterns = [
    # path('', views.ToDoListIndexView.as_view(), name='index'),
    path('', views.ToDoListView.as_view(), name='index'),
]

todo_manager/todo_manager/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import TemplateView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', TemplateView.as_view(template_name='index.html'), name='index'),
    path('todos/', include('todo_list.urls')),
]

todo_manager/todo_list/models.py
from django.db import models


class ToDoItem(models.Model):
    title = models.CharField(max_length=250)
    done = models.BooleanField(default=False)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ('done',)
        verbose_name = 'ToDo Item'
        verbose_name_plural = 'ToDo Items'

    def __str__(self) -> str:
        return f'{self.title}'

todo_manager/todo_list/views.py
from django.http import HttpRequest, HttpResponse
from django.shortcuts import render
from django.views.generic import TemplateView, ListView

from .models import ToDoItem


class ToDoListIndexView(TemplateView):
    template_name = 'todo_list/index.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['todo_items'] = ToDoItem.objects.all()
        return context


class ToDoListView(ListView):
    template_name = 'todo_list/index.html'
    model = ToDoItem
    context_object_name = 'todo_items'



# def index_view(request: HttpRequest) -> HttpResponse:
#     todo_items = ToDoItem.objects.all()
#     return render(
#         request,
#         template_name='todo_list/index.html',
#         context={'todo_items': todo_items},
#     )

todo_manager/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>
    {% block title %}
      Base title
    {% endblock title %}
  </title>
</head>
<body>
{% include 'components/navbar.html' %}

    {% block body %}
      Base body
    {% endblock body %}
<footer>
  &copy; Django TODO App
  {% block footer %}
  
  {% endblock %}
</footer>
</body>
</html>

todo_manager/templates/components/navbar.html
<nav>
  <ul>
    <li><a href="{% url 'index' %}">Home</a></li>
    <li><a href="{% url 'todo_list:index' %}">ToDo List</a></li>
    <li><a href="#">About</a></li>
  </ul>
</nav>

todo_manager/templates/index.html
{% extends 'base.html' %}

{% block title %}
TODO App Index
{% endblock title %}

{% block body %}
<h1>Welcome to our TODO App!</h1>
<h2>Work in progress. 10 years left...</h2>
<h3>It is {% now "jS F Y" %}</h3>
{% endblock body %}

todo_manager/todo_list/templates/todo_list/base.html
{% extends 'base.html' %}

{% block footer %}
  ToDo List
{% endblock %}

todo_manager/todo_list/templates/todo_list/index.html
{%  extends 'todo_list/base.html' %}

{% block title %}
  ToDo List App
{% endblock %}

{% block body %}
  <h1>ToDo List App</h1>
  <h2>ToDos:</h2>
  <ul>
    {% for item in todo_items %}
      <li>
        {{ item.title }}
        {% if item.done %}
        >> DONE
        {% else %}
          >> IN PROGRESS
        {% endif %}
      </li>
    {% endfor %}
  </ul>
{% endblock %}